/*!
 * \defgroup  applicationModule
 * 
 */


/*!
 * \defgroup  definitions Application Constants
 * 
 * \ingroup applicationModule
 */


/*!
 * \defgroup  libraryModules Library Modules Used in the Application.
 */


/*!
 * \mainpage
 *
 * # GENERAL OVERVIEW
 *
 * This Firmware implements the functions of the FW301 Power Service 
 * software specification.
 * 
 * 
 * # DEPENDENCIES AND CONFIGURATION FILES
 * 
 * The Application has been developed with the use of the Microchip Harmony 3
 * libraries. The libraries are a set of source files auto generated by the 
 * Harmony 3 configurator tools and contained into the following directories:
 * - src/config;
 * - src/packs;
 * 
 * ***NOTE: those directories shall never be directly modified since 
 * they are auto-rigenerated every time the generator tool is launched.*** 
 *
 * The libraries make use of the CMSIS 5.4.0 for ARM processors
 * and SAME51_DFP 3.6.130
 *  
 * 
 * # APPLICATION MODULES
 *
 * The Application implements the following modules:
 * - @ref applicationModules : defines common objects to the application modules;
 * - @ref libraryModules : this is the set of the libraries used in the current application;
 *
 * # COMPILATION
 * 
 * This software is compiled with the MPLAB-X IDE 5.50:
 * - Compiler: XC32 Vs 3.1
 * 
 * 
 * # SOFTWARE LICENCING
 *
 * The Application has been developed with the Microchip Harmony 3 libraries 
 * with the Microchip License Agreement conditions as described in:
 * - @ref licenseAgreement 
 *
 * # APPLICATION DOCUMENTATION
 * 
 * This documentation has been produced with Doxygen 
 */



#ifndef _APPLICATION_H    /* Guard against multiple inclusion */
#define _APPLICATION_H

// Defines the Application revision code

/** \addtogroup definitions
 *  @{
*/

#define APP_MAJ_REV   1 //!< Revision Major Number
#define APP_MIN_REV   0 //!< Revision Minor Number
#define APP_SUB_REV   1 //!< Revision build Number

// Defines the Can Dveice Address
#define APP_DEVICE_ID    0x11 //!< Application DEVICE CAN Id address

/** @}*/
        
#endif 