/*!
 * \defgroup  applicationModule Application Modules section
 * 
 */


/*!
 * \defgroup  definitions Application Constants
 * 
 * \ingroup applicationModule
 */


/*!
 * \defgroup  libraryModules Library Modules Used in the Application.
 */


/*!
 * \mainpage
 *
 * # Overview
 *
 * This Firmware implements the functions of the FW301 Power Service 
 * software specification.
 * 
 * 
 * # Dependencies test
 * 
 * The Application has been developed with the use of the Microchip Harmony 3
 * libraries. The libraries are a set of source files auto generated by the 
 * Harmony 3 configurator tools and contained into the following directories:
 * - src/config;
 * - src/packs;
 * 
 * ***NOTE: those directories shall never be directly modified since 
 * they are auto-rigenerated every time the generator tool is launched.*** 
 *
 * The libraries make use of the CMSIS 5.4.0 for ARM processors
 * and SAME51_DFP 3.6.130
 *  
 * 
 * # Modules
 *
 * The Application implements the following modules:
 * - @ref applicationModule : defines common objects to the application modules;
 * - @ref busHwModule : module implementing the Bus Hardwar control;
 * - @ref generatorModule : module implementing the Generator Interface control;
 * - @ref protocolModule : module implementing CAN communication protocol;
 * - @ref libraryModules : this is the set of the libraries used in the current application;
 *
 * # Compilation
 * 
 * This software is compiled with the MPLAB-X IDE 5.50:
 * - Compiler: XC32 Vs 3.1
 * 
 * 
 * # Licensing
 *
 * The Application has been developed with the Microchip Harmony 3 libraries 
 * with the Microchip License Agreement conditions as described in:
 * - @ref licenseAgreement 
 *
 * # Documentation
 * 
 * This documentation has been produced with Doxygen 
 */



#ifndef _APPLICATION_H    /* Guard against multiple inclusion */
#define _APPLICATION_H

// Defines the Application revision code

/** \addtogroup definitions
 *  @{
*/

// Application Revision 
#define MET_CAN_APP_MAJ_REV   1 //!< Revision Major Number
#define MET_CAN_APP_MIN_REV   0 //!< Revision Minor Number
#define MET_CAN_APP_SUB_REV   1 //!< Revision build Number

// Can Module Definitions
#define MET_CAN_APP_DEVICE_ID     0x1 //!< Application DEVICE CAN Id address
#define MET_CAN_STATUS_REGISTERS    3 //!< Defines the total number of implemented STATUS registers 
#define MET_CAN_DATA_REGISTERS      1 //!< Defines the total number of implemented Application DATA registers 
#define MET_CAN_PARAM_REGISTERS     12 //!< Defines the total number of implemented PARAMETER registers 

/** @}*/
        
#endif 